#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <stick_icons.h>

int32_t stick_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm stick!");

    return 0;
}
